seed: 1001
__set_seed: !apply:torch.manual_seed [!ref <seed>]
model_name: wav2vec2-base-960h
root: !PLACEHOLDER
output_folder: !ref <root>/attacks/none/<model_name>/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>
log: !ref <output_folder>/log.txt
tokenizers_folder: !ref <root>/tokenizers

attack_class: null
save_audio_path: null

pretrained_tokenizer_path: !ref <root>/trainings/<model_name>/tokenizer
tokenizer: !new:speechbrain.dataio.encoder.CTCTextEncoder

target_brain_class: !name:robust_speech.models.wav2vec2_fine_tune.W2VASR
target_brain_hparams_file: !ref model_configs/<model_name>.yaml

dataset_prepare_fct: !name:robust_speech.data.librispeech.prepare_librispeech
dataio_prepare_fct: !name:robust_speech.data.librispeech.dataio_prepare

# Data files
data_folder: !ref <root>/data/LibriSpeech # e.g, /localscratch/LibriSpeech
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
test_splits: ["test-clean-short"]
skip_prep: True
ckpt_interval_minutes: 15 # save checkpoint every N min
test_csv:
   - !ref <data_folder>/csv/test-clean-short.csv
# Training parameters
# To make Transformers converge, the global bath size should be large enough.
# The global batch size is computed as batch_size * n_gpus * gradient_accumulation.
# Empirically, we found that this value should be >= 128.
# Please, set your parameters accordingly.
batch_size: 1 # This works for 2x GPUs with 32GB
avoid_if_longer_than: 24.0
sorting: random

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80

# Decoding parameters (only for text_pipeline)
blank_index: 0
bos_index: 1
eos_index: 2

valid_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1


logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
acc_computer: !name:speechbrain.utils.Accuracy.AccuracyStats

# The pretrainer allows a mapping between pretrained files and instances that
# are declared in the yaml. E.g here, we will download the file lm.ckpt
# and it will be loaded into "lm" which is pointing to the <lm_model> defined
# before.

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <tokenizers_folder>/<model_name>
   loadables:
      tokenizer: !ref <tokenizer>
   paths:
      tokenizer: !ref <pretrained_tokenizer_path>/tokenizer.ckpt
