# ################################
# Model: wav2vec2 BASE (pretraining)
# Authors: Titouan Parcollet 2021, Yan Gao 2021
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1000
__set_seed: !apply:torch.manual_seed [!ref <seed>]
root: !PLACEHOLDER
output_folder: !ref <root>/trainings/wav2vec2_pretrain_char/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# URL for the base english wav2vec2 model.
wav2vec2_hub: facebook/wav2vec2-base

brain_class: !name:robust_speech.models.wav2vec2_pretrain.W2VPretrain
dataset_prepare_fct: !name:robust_speech.data.librispeech.prepare_librispeech
dataio_prepare_fct: !name:robust_speech.data.dataio.dataio_prepare

attack_class: null

# URL for the HuggingFace model we want to pretrain (BASE here)
#wav2vec2_hub: facebook/wav2vec2-base

# Data files
data_folder: !ref <root>/data/LibriSpeech # e.g, /localscratch/LibriSpeech
csv_folder: !ref <data_folder>/csv # e.g, /localscratch/LibriSpeech
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
#data_folder_rirs: !ref <data_folder>
train_splits: ["train-clean-100", "train-clean-360", "train-other-500"]
dev_splits: ["dev-clean"]
test_splits: ["test-clean", "test-other"]
ckpt_interval_minutes: 15 # save checkpoint every N min
train_csv: !ref <data_folder>/csv/train.csv
valid_csv: !ref <data_folder>/csv/dev-clean.csv
test_csv:
   - !ref <data_folder>/csv/test-clean.csv
skip_prep: True

# We remove utterance slonger than 10s in the train/dev/test sets as
# longer sentences certainly correspond to "open microphones".
avoid_if_longer_than: 17.0
avoid_if_shorter_than: 1.0

# Training parameters
# Parameters are corresponding the the ones reported in the official wav2vec2
# paper (for the masking).
mask_length: 10
mask_prob: 0.65
freeze_wav2vec: False

number_of_epochs: 100
lr_adam: 2.0 # This will get reduced by the training scheduler
weight_decay: 0.01
d_model: 768  # Needed by the scheduler. 768 is for the BASE w2v2
sorting: ascending
auto_mix_prec: False
sample_rate: 16000

gradient_accumulation: 1
# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 12 per GPU to fit 32GB of VRAM
# IMPORTANT: To train w2v2 model, we recommand to have the effective batch_size
# higher than 100 (batch_size * nb_gpu * gradient_accumulation)
# Examples are:
# 32 Tesla V100 32GB — 12 * 32 * 1
# 4 Tesla V100 32GB — 12 * 4 * {6-8}

batch_size: 8
val_batch_size: 2
test_batch_size: 1

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>

valid_dataloader_opts:
   batch_size: !ref <val_batch_size>

test_dataloader_opts:
   batch_size: !ref <test_batch_size>

blank_index: 0
bos_index: 1
eos_index: 2
#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

wav2vec2: !new:robust_speech.models.modules.hf_wav2vec2.AdvHuggingFaceWav2Vec2Pretrain
    source: !ref <wav2vec2_hub>
    save_path: !ref <save_folder>/wav2vec2_checkpoints
    mask_prob: !ref <mask_prob>
    mask_length: !ref <mask_length>

modules:
    wav2vec2: !ref <wav2vec2>

opt_class: !name:torch.optim.AdamW
    lr: 0 # Will be changed by the scheduler, but we start at 0!
    betas: (0.9, 0.98)
    eps: 0.000000001
    weight_decay: !ref <weight_decay>

tokenizer: !new:speechbrain.dataio.encoder.CTCTextEncoder

noam_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr_adam>
    n_warmup_steps: 25000
    model_size: !ref <d_model>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    allow_partial_load: True
    checkpoints_dir: !ref <save_folder>
    recoverables:
        wav2vec2: !ref <wav2vec2>
        scheduler: !ref <noam_annealing>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
